theme: jekyll-theme-minimal
title: Ghoshpukur College - Ambari
description: This page is used to inform visitors regarding the privacy policies with the collection, use, disclosure of Personal Information, and other related informations if anyone decided to use the  Ghoshpukur College - Ambari App. This policy extends to all individuals using the app, including students, staff, and other vested parties connected to Ghoshpukur College - Ambari App.
